### ISSUE TITLE
increase speed

### ISSUE THREAD

**Issue by Labs22** [jm33-m0/massExpConsole#33]
check this out: https://i.imgur.com/w2bnUIl.png

I took a while to collect 59M of targets and just lauch a personal exploit.
No bugs. Works perfect. Awsome job but
 Mec uses only 10% cpu,10% of internet connection and 5% of memory.

How we can make this more faster and optimized?
I'll love to make my collab.
1800 hours is too long.
BTW how much hosts do you have tested so far?

Have nice night.

Best Regards. - Luan

**Comment by jm33-m0** [comment]
if you want faster subprocess launching, you can reduce the sleep time here:
https://github.com/jm33-m0/massExpConsole/blob/48c2cc43a30127735a05ba0af48adf0512f3d594/lib/cli/main.py#L453
currently i set it to `0.11` seconds, which might be too conservative for large target sets
i will remove it in next commit

due to multi-**process** nature, mec will use as many CPU as it needs, you only need to increase the job count

**Comment by jm33-m0** [comment]
also, the progress bar only indicates how many processes have been started, but we usually don't want this #32 
so im gonna change the way progress bar works, hopefully it will be more useful
